# --- Version Management ---

# Extract version from booster composer.json
function get_booster_version() {
    local booster_composer="${BOOSTER_INTERNAL_PATH}/composer.json"

    if ! command -v jq &> /dev/null; then
        # Fallback if jq is not installed
        if [ -f "$booster_composer" ]; then
            grep '"version":' "$booster_composer" | head -n 1 | sed -E 's/.*"version": "([^"]+)".*/\1/' || echo "unknown"
        else
            echo "unknown"
        fi
        return
    fi

    if [ -f "$booster_composer" ]; then
        jq -r '.version // "unknown"' "$booster_composer"
    else
        echo "unknown"
    fi
}


# Get the currently installed booster version
function get_installed_version() {
    local version_file=".booster-version"
    if [ -f "$version_file" ]; then
        grep "^VERSION=" "$version_file" 2>/dev/null | cut -d'=' -f2 || echo ""
    else
        echo ""
    fi
}

# Create or update the version stamp file
function create_version_stamp() {
    local version="$1"
    local install_mode="${2:-full}"
    local version_file=".booster-version"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')

    cat > "$version_file" << EOF
# PHP Booster Version Stamp
# This file tracks which booster version was integrated into this project
# Generated by integrate_booster.sh

VERSION=$version
INSTALLED_DATE=$timestamp
INTEGRATION_METHOD=script
INSTALL_MODE=$install_mode
EOF

    log "Created version stamp: $version (installed $timestamp, mode: $install_mode)"
}

# Show version information and upgrade status
function show_version_info() {
    local current_version="$1"
    local installed_version
    installed_version=$(get_installed_version)

    if [ -n "$installed_version" ]; then
        echo -e "${GREEN}[INFO]${NC} Previous booster installation detected: $installed_version"
        echo -e "${GREEN}[INFO]${NC} Current booster version: $current_version"

        if [ "$installed_version" != "$current_version" ]; then
            echo -e "${YELLOW}[UPGRADE]${NC} This will upgrade your booster from $installed_version to $current_version"
        else
            echo -e "${GREEN}[INFO]${NC} Re-integrating same version (idempotent operation)"
        fi
    else
        echo -e "${GREEN}[INFO]${NC} Installing PHP Booster version: $current_version"
    fi
}
