#!/usr/bin/env bash

if ! ddev composer generate-api-spec; then
    echo "Failed to generate the API documentation"
    exit 1
fi

# Check if openapi.yml has been modified and exit if it's not
git diff --name-only | grep -q openapi.yml || exit 0

# Generate the HTML API documentation
ddev pnpm generate:api-doc:html || true

git add documentation
git commit -m "chore: update API documentation"
