#!/usr/bin/env bash

ROOT=$(git rev-parse --show-toplevel)
runner="$ROOT/tools/runner.sh"

# Check if MERGE_HEAD exists
if [ -f "$GIT_DIR/MERGE_HEAD" ]; then
    # Skip the hook during a merge
    exit 0
fi

# Check if phpunit is installed or pest and run the tests accordingly - don't exit
if bash "$runner" composer show | grep -q "pestphp/pest"; then
    echo "Running Pest tests..."
    bash "$runner" composer test:coverage
    echo "Tests passed successfully"
fi

if bash "$runner" composer show | grep -q "phpunit/phpunit"; then
    echo "Running PHPUnit tests..."
    bash "$runner" composer test:coverage
    echo "Tests passed successfully"
fi

# Check if swagger-php is installed
if ! bash "$runner" composer show | grep -q "zircote/swagger-php"; then
    echo "swagger-php is not installed. Skipping API documentation generation..."
    exit 0
fi

if ! bash "$runner" composer generate-api-spec; then
    echo "Failed to generate the API documentation"
    exit 1
fi

# Check if openapi.yml has been modified and exit if it's not
git diff --name-only | grep -q openapi.yml || exit 0

# Generate the HTML API documentation
bash "$runner" pnpm generate:api-doc:html

git add documentation
git commit -m "chore: update API documentation"
