#!/usr/bin/env bash

# Since git hooks must be POSIX compliant, we can't use bash features.
# This script is a wrapper around the actual script that does the work.

GIT_HOOKS_PATH=$(git config core.hooksPath)

bash "$GIT_HOOKS_PATH/../pre-push.bash"
